import os, datetime, pathlib, jinja2

OUT_DIR = pathlib.Path('content/posts')
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Config – you can change these defaults or override with env vars
TITLE = os.getenv('POST_TITLE', 'Data & Tech Weekly: Auto Update')
TAGS = ["data", "automation", "python"]
AUTHOR = os.getenv('AUTHOR_NAME', 'Jeanalyst')

date = datetime.date.today().isoformat()
slug = TITLE.lower().replace(' ', '-').replace(':', '').replace('/', '-')
filename = f"{date}-{slug}.md"
path = OUT_DIR / filename

template = """---
title: "{{ title }}"
date: "{{ date }}"
tags: {{ tags }}
author: "{{ author }}"
published: false   # change to true after review
---

{{ intro }}

<!-- This is an autogenerated draft. Please edit before merging. -->
"""

intro = "This is an autogenerated draft post. Replace this section with your analysis, code snippets, or data visuals."

env = jinja2.Environment()
content = env.from_string(template).render(
    title=TITLE,
    date=date,
    tags=TAGS,
    author=AUTHOR,
    intro=intro
)

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"Generated: {path}")
